import {
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  normalizeAgentTurnPayload,
  sortAgentSessions,
} from './normalizers.js'
import { createAgentSessionStoreMethods } from './session-store.js'
import { createAgentRuntimeMethods } from './runtime.js'
import { createAgentUiMethods } from './sessions-ui.js'
export {
  buildAnalysisTaskConfirmation,
  focusAnalysisTaskPanel,
  getAnalysisTaskDefinition,
  getAnalysisTaskDefinitions,
  resolveAnalysisTaskKeyFromTrace,
  runAnalysisTask,
} from './analysis-task-registry.js'

function createAnalysisAgentInitialState() {
  return {
    agentWorkspaceView: 'chat',
    agentConversationId: '',
    agentInput: '',
    agentLoading: false,
    agentStatus: 'idle',
    agentStage: 'gating',
    agentCards: [],
    agentDecision: { summary: '', mode: 'judgment', strength: 'weak', canAct: false },
    agentSupport: [],
    agentCounterpoints: [],
    agentActions: [],
    agentBoundary: [],
    agentExecutionTrace: [],
    agentUsedTools: [],
    agentCitations: [],
    agentResearchNotes: [],
    agentAuditIssues: [],
    agentNextSuggestions: [],
    agentPanelPayloads: {},
    agentClarificationQuestion: '',
    agentClarificationOptions: [],
    agentClarificationDraft: '',
    agentClarificationSubmitting: false,
    agentRiskPrompt: '',
    agentPendingTaskConfirmation: null,
    agentError: '',
    agentContextSummary: {},
    agentPlan: { steps: [], followupSteps: [], followupApplied: false, summary: '' },
    agentPlanExpanded: false,
    agentTraceExpanded: false,
    agentPanelPreloadNotes: [],
    agentPreloadedPanelKeys: [],
    agentRiskConfirmations: [],
    agentMessages: [],
    agentThinkingTimeline: [],
    agentReasoningBlocks: [],
    agentStreamingMessageId: '',
    agentStreamState: 'idle',
    agentStreamStartedAt: 0,
    agentStreamElapsedTick: 0,
    agentStreamElapsedTimer: null,
    agentProgrammaticScrollUntil: 0,
    agentThinkingExpanded: false,
    agentSessions: [],
    activeAgentSessionId: '',
    agentSessionsLoaded: false,
    agentSessionsLoading: false,
    agentSessionHydrating: false,
    agentSessionDetailLoadingId: '',
    agentSessionDetailRequestToken: 0,
    agentTurnAbortController: null,
    agentRunRegistry: {},
    agentSessionMenuId: '',
    agentRenameDialogOpen: false,
    agentRenameSessionId: '',
    agentRenameInput: '',
    agentTools: [],
    agentToolsLoaded: false,
    agentToolsLoading: false,
    agentToolsError: '',
    agentToolDetailDialogOpen: false,
    agentActiveToolDetailName: '',
    agentTabs: {
      summaryTab: {
        id: 'summary',
        frozen: true,
        createdAt: '',
        content: {},
        evidenceRefs: [],
      },
      summaryTabs: [],
      followupTabs: [],
      activeTabId: '',
      followupLimit: 6,
      nextFollowupNumber: 1,
    },
    agentCreateTabMenuOpen: false,
    agentSummaryReadiness: {
      checked: false,
      ready: false,
      missingTasks: [],
      reused: [],
      fetched: [],
    },
    agentSummaryLoading: false,
    agentSummaryGenerating: false,
    agentSummaryProgressPhase: '',
    agentSummaryStreamSections: {},
    agentSummaryError: '',
    agentSummaryWarnings: [],
    summaryTaskBoard: {
      runState: 'idle',
      tasks: [],
      lastRunAt: '',
    },
    summaryTaskLogTrackers: {},
  }
}

function createAnalysisAgentSessionMethods() {
  return {
    ...createAgentSessionStoreMethods(),
    ...createAgentRuntimeMethods(),
    ...createAgentUiMethods(),
  }
}

export {
  createAnalysisAgentInitialState,
  createAnalysisAgentSessionMethods,
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentTurnPayload,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  sortAgentSessions,
}
