from __future__ import annotations

from dataclasses import dataclass
from typing import Awaitable, Callable, Dict, List

from .schemas import ToolResult, ToolSpec
from .tool_adapters.analysis_tools import (
    analyze_poi_mix_from_scope,
    analyze_target_supply_gap_from_scope,
    detect_commercial_hotspots_from_scope,
    read_h3_structure_analysis,
    read_nightlight_pattern_analysis,
    read_poi_structure_analysis,
    read_population_profile_analysis,
    read_road_pattern_analysis,
)
from .tool_adapters.business_tools import run_business_site_advice
from .tool_adapters.capability_tools import (
    analyze_poi_structure,
    analyze_spatial_structure,
    get_area_data_bundle,
    infer_area_labels,
    score_site_candidates_tool,
)
from .tool_adapters.h3_tools import build_h3_grid_from_scope, compute_h3_metrics_from_scope_and_pois
from .tool_adapters.nightlight_tools import compute_nightlight_overview_from_scope
from .tool_adapters.poi_tools import fetch_pois_in_scope
from .tool_adapters.population_tools import compute_population_overview_from_scope
from .tool_adapters.result_tools import read_current_results
from .tool_adapters.road_tools import compute_road_syntax_from_scope
from .tool_adapters.scenario_tools import (
    run_area_character_pack,
    run_placeholder_scene_pack,
    run_site_selection_pack,
)
from .tool_adapters.scope_tools import read_current_scope

ToolRunner = Callable[..., Awaitable[ToolResult]]


@dataclass(frozen=True)
class RegisteredTool:
    spec: ToolSpec
    runner: ToolRunner


def _named_placeholder(tool_name: str) -> ToolRunner:
    async def runner(*, arguments, snapshot, artifacts, question):
        result = await run_placeholder_scene_pack(
            arguments=arguments,
            snapshot=snapshot,
            artifacts=artifacts,
            question=question,
        )
        return result.model_copy(update={"tool_name": tool_name})

    return runner


def _register(spec: ToolSpec, runner: ToolRunner) -> RegisteredTool:
    return RegisteredTool(spec=spec, runner=runner)


def _tool_spec(
    *,
    name: str,
    description: str,
    category: str,
    layer: str,
    ui_tier: str,
    data_domain: str,
    capability_type: str,
    scene_type: str = "general",
    llm_exposure: str = "secondary",
    toolkit_id: str = "",
    default_policy_key: str = "",
    evidence_contract: List[str] | None = None,
    applicable_scenarios: List[str] | None = None,
    cautions: List[str] | None = None,
    requires: List[str] | None = None,
    produces: List[str] | None = None,
    input_schema: Dict | None = None,
    output_schema: Dict | None = None,
    readonly: bool = False,
    cost_level: str = "safe",
    risk_level: str = "safe",
    timeout_sec: int = 30,
    cacheable: bool = False,
) -> ToolSpec:
    return ToolSpec(
        name=name,
        description=description,
        category=category,
        layer=layer,
        ui_tier=ui_tier,
        data_domain=data_domain,
        capability_type=capability_type,
        scene_type=scene_type,
        llm_exposure=llm_exposure,
        toolkit_id=toolkit_id,
        default_policy_key=default_policy_key,
        evidence_contract=list(evidence_contract or []),
        applicable_scenarios=list(applicable_scenarios or []),
        cautions=list(cautions or []),
        requires=list(requires or []),
        produces=list(produces or []),
        input_schema=input_schema or {"type": "object", "properties": {}, "additionalProperties": False},
        output_schema=output_schema or {"type": "object", "properties": {}, "additionalProperties": True},
        readonly=readonly,
        cost_level=cost_level,
        risk_level=risk_level,
        timeout_sec=timeout_sec,
        cacheable=cacheable,
    )


def get_tool_registry() -> Dict[str, RegisteredTool]:
    registry: Dict[str, RegisteredTool] = {}

    registry["read_current_scope"] = _register(
        _tool_spec(
            name="read_current_scope",
            description="读取当前 analysis snapshot 中的 scope / isochrone / polygon",
            category="information",
            layer="L1",
            ui_tier="foundation",
            data_domain="general",
            capability_type="fetch",
            llm_exposure="primary",
            evidence_contract=["scope_polygon"],
            applicable_scenarios=["所有地图分析任务起步"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "has_scope": {"type": "boolean"},
                    "active_panel": {"type": "string"},
                },
                "required": ["has_scope", "active_panel"],
                "additionalProperties": True,
            },
            produces=["scope_polygon", "isochrone_feature"],
            readonly=True,
        ),
        read_current_scope,
    )
    registry["read_current_results"] = _register(
        _tool_spec(
            name="read_current_results",
            description="读取当前 analysis snapshot 中已存在的结果摘要",
            category="information",
            layer="L1",
            ui_tier="foundation",
            data_domain="general",
            capability_type="fetch",
            llm_exposure="primary",
            evidence_contract=[
                "current_poi_summary",
                "current_h3_summary",
                "current_population_summary",
                "current_nightlight_summary",
                "current_road_summary",
            ],
            applicable_scenarios=["所有地图分析任务复用已有结果"],
            produces=[
                "current_pois",
                "current_poi_summary",
                "current_h3_summary",
                "current_road_summary",
                "current_population_summary",
                "current_nightlight_summary",
            ],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "poi_count": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "has_h3_summary": {"type": "boolean"},
                    "has_road_summary": {"type": "boolean"},
                    "has_population_summary": {"type": "boolean"},
                    "has_nightlight_summary": {"type": "boolean"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_current_results,
    )
    registry["fetch_pois_in_scope"] = _register(
        _tool_spec(
            name="fetch_pois_in_scope",
            description="在当前 scope 内抓取 POI 数据",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="poi",
            capability_type="fetch",
            llm_exposure="secondary",
            requires=["scope_polygon"],
            produces=["current_pois", "current_poi_summary"],
            evidence_contract=["poi.count", "poi.source"],
            applicable_scenarios=["基础数据补齐", "业态样本抓取", "选址前置"],
            cautions=["不能单独用于判断建店可行性，需结合人口、活力和竞品视角"],
            input_schema={
                "type": "object",
                "properties": {
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "types": {"type": "string"},
                    "keywords": {"type": "string"},
                    "max_count": {"type": "integer", "minimum": 1, "maximum": 5000},
                    "year": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "poi_count": {"type": "integer"},
                    "source": {"type": "string"},
                    "types": {"type": "string"},
                    "keywords": {"type": "string"},
                },
                "required": ["poi_count", "source", "types", "keywords"],
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=120,
        ),
        fetch_pois_in_scope,
    )
    registry["build_h3_grid_from_scope"] = _register(
        _tool_spec(
            name="build_h3_grid_from_scope",
            description="根据当前 scope 生成 H3 网格",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="grid",
            capability_type="transform",
            llm_exposure="hidden",
            requires=["scope_polygon"],
            produces=["current_h3_grid"],
            applicable_scenarios=["网格化预处理"],
            cautions=["仅生成网格，不直接形成业务判断"],
            input_schema={
                "type": "object",
                "properties": {
                    "resolution": {"type": "integer", "minimum": 0},
                    "include_mode": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "grid_count": {"type": "integer"},
                    "resolution": {"type": "integer"},
                },
                "required": ["grid_count", "resolution"],
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=60,
        ),
        build_h3_grid_from_scope,
    )
    registry["compute_h3_metrics_from_scope_and_pois"] = _register(
        _tool_spec(
            name="compute_h3_metrics_from_scope_and_pois",
            description="结合 scope 和 POI 计算 H3 指标",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="grid",
            capability_type="analyze",
            llm_exposure="secondary",
            requires=["scope_polygon"],
            produces=["current_h3", "current_h3_grid", "current_h3_summary", "current_h3_charts"],
            evidence_contract=["h3.summary.grid_count", "h3.summary.avg_density_poi_per_km2"],
            applicable_scenarios=["空间分布分析", "机会网格识别", "选址前置"],
            cautions=["只提供空间统计，不直接替代调性或选址结论"],
            input_schema={
                "type": "object",
                "properties": {
                    "resolution": {"type": "integer", "minimum": 0},
                    "include_mode": {"type": "string"},
                    "min_overlap_ratio": {"type": "number", "minimum": 0},
                    "neighbor_ring": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "grid_count": {"type": "integer"},
                    "poi_count": {"type": "integer"},
                },
                "required": ["grid_count", "poi_count"],
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=180,
        ),
        compute_h3_metrics_from_scope_and_pois,
    )
    registry["compute_population_overview_from_scope"] = _register(
        _tool_spec(
            name="compute_population_overview_from_scope",
            description="根据当前 scope 计算人口概览摘要",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="population",
            capability_type="analyze",
            llm_exposure="primary",
            requires=["scope_polygon"],
            produces=["current_population", "current_population_summary"],
            evidence_contract=["population.summary.total_population", "population.summary.male_ratio"],
            applicable_scenarios=["人口底盘查看", "居住适宜性", "区域画像"],
            cautions=["不能直接推断消费能力或客流"],
            default_policy_key="community_life_circle",
            input_schema={
                "type": "object",
                "properties": {
                    "coord_type": {"type": "string", "enum": ["gcj02", "wgs84"]},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "total_population": {"type": "number"},
                    "male_ratio": {"type": "number"},
                    "female_ratio": {"type": "number"},
                },
                "required": ["total_population", "male_ratio", "female_ratio"],
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=180,
        ),
        compute_population_overview_from_scope,
    )
    registry["compute_nightlight_overview_from_scope"] = _register(
        _tool_spec(
            name="compute_nightlight_overview_from_scope",
            description="根据当前 scope 计算夜光概览摘要",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="nightlight",
            capability_type="analyze",
            llm_exposure="primary",
            requires=["scope_polygon"],
            produces=["current_nightlight", "current_nightlight_summary"],
            evidence_contract=["nightlight.summary.total_radiance", "nightlight.summary.max_radiance"],
            applicable_scenarios=["活力评估", "夜间消费判断", "区域画像"],
            cautions=["夜光只可视作活力 proxy，不能直接等同客流"],
            default_policy_key="district_summary",
            input_schema={
                "type": "object",
                "properties": {
                    "coord_type": {"type": "string", "enum": ["gcj02", "wgs84"]},
                    "year": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "total_radiance": {"type": "number"},
                    "mean_radiance": {"type": "number"},
                    "peak_radiance": {"type": "number"},
                    "lit_pixel_ratio": {"type": "number"},
                },
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=180,
        ),
        compute_nightlight_overview_from_scope,
    )
    registry["compute_road_syntax_from_scope"] = _register(
        _tool_spec(
            name="compute_road_syntax_from_scope",
            description="根据当前 scope 计算路网句法摘要",
            category="action",
            layer="L1",
            ui_tier="foundation",
            data_domain="road",
            capability_type="analyze",
            llm_exposure="primary",
            requires=["scope_polygon"],
            produces=["current_road", "current_road_summary"],
            evidence_contract=["road.summary.node_count", "road.summary.edge_count"],
            applicable_scenarios=["路网可达性", "站城分析", "区域画像"],
            cautions=["不应把路网指标直接替代交通流量结论"],
            default_policy_key="community_life_circle",
            input_schema={
                "type": "object",
                "properties": {
                    "mode": {"type": "string"},
                    "graph_model": {"type": "string"},
                    "highway_filter": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "node_count": {"type": "integer"},
                    "edge_count": {"type": "integer"},
                },
                "required": ["node_count", "edge_count"],
                "additionalProperties": True,
            },
            cost_level="expensive",
            risk_level="safe",
            timeout_sec=900,
        ),
        compute_road_syntax_from_scope,
    )

    registry["get_area_data_bundle"] = _register(
        _tool_spec(
            name="get_area_data_bundle",
            description="按参数策略表补齐区域画像所需的 POI/H3/人口/夜光/路网基础数据包",
            category="action",
            layer="L2",
            ui_tier="capability",
            data_domain="general",
            capability_type="fetch",
            llm_exposure="primary",
            toolkit_id="area_character_pack",
            default_policy_key="district_summary",
            evidence_contract=["current_area_data_bundle", "policy_key"],
            applicable_scenarios=["区域画像", "调性判断", "前期研究"],
            cautions=["优先作为场景工具内部步骤；单独调用时仍需后续解释层工具"],
            requires=["scope_polygon"],
            produces=["current_area_data_bundle", "current_poi_summary", "current_h3_summary", "current_population_summary", "current_nightlight_summary", "current_road_summary"],
            input_schema={
                "type": "object",
                "properties": {
                    "policy_key": {"type": "string"},
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "mode": {"type": "string"},
                    "resolution": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": False,
            },
        ),
        get_area_data_bundle,
    )
    registry["analyze_poi_structure"] = _register(
        _tool_spec(
            name="analyze_poi_structure",
            description="基于 POI 结构生成业态主导、复合度和商业画像",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="poi",
            capability_type="analyze",
            llm_exposure="primary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_poi_structure_analysis", "current_business_profile"],
            applicable_scenarios=["区域画像", "商圈分析", "功能定位"],
            cautions=["不能替代选址打分"],
            produces=["current_poi_structure_analysis", "current_business_profile"],
            readonly=True,
            cost_level="normal",
        ),
        analyze_poi_structure,
    )
    registry["analyze_spatial_structure"] = _register(
        _tool_spec(
            name="analyze_spatial_structure",
            description="整理 H3、人口、夜光、路网结构，形成空间结构概览",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="grid",
            capability_type="analyze",
            llm_exposure="primary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=[
                "current_h3_structure_analysis",
                "current_population_profile_analysis",
                "current_nightlight_pattern_analysis",
                "current_road_pattern_analysis",
            ],
            applicable_scenarios=["区域调性", "活力判断", "空间结构分析"],
            cautions=["输出是结构概览，不直接给经营建议"],
            produces=[
                "current_h3_structure_analysis",
                "current_population_profile_analysis",
                "current_nightlight_pattern_analysis",
                "current_road_pattern_analysis",
            ],
            readonly=True,
            cost_level="normal",
        ),
        analyze_spatial_structure,
    )
    registry["infer_area_labels"] = _register(
        _tool_spec(
            name="infer_area_labels",
            description="基于规则标签引擎输出区域标签、主导功能和证据命中",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="interpret",
            llm_exposure="primary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_area_character_labels", "rule_hits"],
            applicable_scenarios=["区域调性判断", "片区定位", "概念研究"],
            cautions=["标签来自规则命中，不能替代详细控规和财务测算"],
            produces=["current_area_character_labels"],
            readonly=True,
            cost_level="normal",
        ),
        infer_area_labels,
    )
    registry["score_site_candidates"] = _register(
        _tool_spec(
            name="score_site_candidates",
            description="程序化计算候选格得分与排序，输出优势、风险和推荐顺序",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="decide",
            llm_exposure="primary",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            default_policy_key="business_catchment_1km",
            evidence_contract=["current_site_candidate_scores", "current_target_supply_gap"],
            applicable_scenarios=["建店选址", "品牌补位", "候选点排序"],
            cautions=["排序结果依赖当前候选格证据，不能替代租金和财务测算"],
            produces=["current_site_candidate_scores", "current_target_supply_gap"],
            input_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                },
                "additionalProperties": False,
            },
            readonly=True,
            cost_level="normal",
        ),
        score_site_candidates_tool,
    )

    registry["run_area_character_pack"] = _register(
        _tool_spec(
            name="run_area_character_pack",
            description="固定流程完成区域总体调性判断，输出标签、主导功能和证据链",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="general",
            capability_type="decide",
            scene_type="area_character",
            llm_exposure="primary",
            toolkit_id="area_character_pack",
            default_policy_key="district_summary",
            evidence_contract=["area_character_pack", "current_area_character_labels"],
            applicable_scenarios=["区域总体调性", "片区功能定位", "前期策划"],
            cautions=["不能替代控规、财务测算或详细专项研究"],
            requires=["scope_polygon"],
            produces=["area_character_pack", "current_area_character_labels"],
            input_schema={
                "type": "object",
                "properties": {
                    "area": {"type": "string"},
                    "analysis_mode": {"type": "string"},
                    "policy_key": {"type": "string"},
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "mode": {"type": "string"},
                    "resolution": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "character_tags": {"type": "array"},
                    "dominant_functions": {"type": "array"},
                    "activity_period": {"type": "string"},
                    "crowd_traits": {"type": "array"},
                    "spatial_temperament": {"type": "string"},
                    "evidence_chain": {"type": "array"},
                    "confidence": {"type": "string"},
                },
                "additionalProperties": True,
            },
            cost_level="normal",
            timeout_sec=600,
        ),
        run_area_character_pack,
    )
    registry["run_site_selection_pack"] = _register(
        _tool_spec(
            name="run_site_selection_pack",
            description="固定流程完成建店选址/补位分析，输出候选点排序、优劣势和证据链",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="commerce",
            capability_type="decide",
            scene_type="site_selection",
            llm_exposure="primary",
            toolkit_id="site_selection_pack",
            default_policy_key="business_catchment_1km",
            evidence_contract=["site_selection_pack", "current_site_candidate_scores", "current_target_supply_gap"],
            applicable_scenarios=["商业建店选址", "品牌补位", "候选点排序"],
            cautions=["不含租金、财务和真实竞品经营数据，结果用于预筛"],
            requires=["scope_polygon"],
            produces=["site_selection_pack", "current_site_candidate_scores", "current_target_supply_gap"],
            input_schema={
                "type": "object",
                "properties": {
                    "area": {"type": "string"},
                    "place_type": {"type": "string"},
                    "brand_profile": {"type": "string"},
                    "policy_key": {"type": "string"},
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "year": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "mode": {"type": "string"},
                    "resolution": {"type": "integer", "minimum": 0},
                    "include_mode": {"type": "string"},
                    "min_overlap_ratio": {"type": "number", "minimum": 0},
                    "neighbor_ring": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "candidate_sites": {"type": "array"},
                    "ranking": {"type": "array"},
                    "strengths": {"type": "array"},
                    "risks": {"type": "array"},
                    "not_recommended_reason": {"type": "string"},
                    "evidence_chain": {"type": "array"},
                    "confidence": {"type": "string"},
                },
                "additionalProperties": True,
            },
            cost_level="expensive",
            timeout_sec=900,
        ),
        run_site_selection_pack,
    )

    registry["run_vitality_assessment_pack"] = _register(
        _tool_spec(
            name="run_vitality_assessment_pack",
            description="预留的活力评估场景工具包",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="nightlight",
            capability_type="decide",
            scene_type="vitality",
            llm_exposure="hidden",
            toolkit_id="vitality_pack",
            applicable_scenarios=["活力评估"],
            cautions=["当前版本尚未实现"],
            requires=["scope_polygon"],
        ),
        _named_placeholder("run_vitality_assessment_pack"),
    )
    registry["run_tod_pack"] = _register(
        _tool_spec(
            name="run_tod_pack",
            description="预留的 TOD / 站城分析工具包",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="road",
            capability_type="decide",
            scene_type="tod",
            llm_exposure="hidden",
            toolkit_id="tod_pack",
            default_policy_key="tod_station_area",
            applicable_scenarios=["TOD / 站城分析"],
            cautions=["当前版本尚未实现"],
            requires=["scope_polygon"],
        ),
        _named_placeholder("run_tod_pack"),
    )
    registry["run_livability_pack"] = _register(
        _tool_spec(
            name="run_livability_pack",
            description="预留的居住适宜性分析工具包",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="population",
            capability_type="decide",
            scene_type="livability",
            llm_exposure="hidden",
            toolkit_id="livability_pack",
            applicable_scenarios=["居住适宜性"],
            cautions=["当前版本尚未实现"],
            requires=["scope_polygon"],
        ),
        _named_placeholder("run_livability_pack"),
    )
    registry["run_facility_gap_pack"] = _register(
        _tool_spec(
            name="run_facility_gap_pack",
            description="预留的公服配置缺口识别工具包",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="commerce",
            capability_type="decide",
            scene_type="facility_gap",
            llm_exposure="hidden",
            toolkit_id="facility_gap_pack",
            applicable_scenarios=["公服配置缺口识别"],
            cautions=["当前版本尚未实现"],
            requires=["scope_polygon"],
        ),
        _named_placeholder("run_facility_gap_pack"),
    )
    registry["run_renewal_priority_pack"] = _register(
        _tool_spec(
            name="run_renewal_priority_pack",
            description="预留的更新优先级排序工具包",
            category="action",
            layer="L2",
            ui_tier="scenario",
            data_domain="general",
            capability_type="decide",
            scene_type="renewal_priority",
            llm_exposure="hidden",
            toolkit_id="renewal_priority_pack",
            applicable_scenarios=["更新优先级排序"],
            cautions=["当前版本尚未实现"],
            requires=["scope_polygon"],
        ),
        _named_placeholder("run_renewal_priority_pack"),
    )

    registry["read_poi_structure_analysis"] = _register(
        _tool_spec(
            name="read_poi_structure_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的 POI 业态结构分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="poi",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_poi_structure_analysis"],
            applicable_scenarios=["兼容旧规划链路", "POI 结构复用"],
            produces=["current_poi_structure_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "dominant_categories": {"type": "array"},
                    "dining_ratio": {"type": "number"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_poi_structure_analysis,
    )
    registry["read_h3_structure_analysis"] = _register(
        _tool_spec(
            name="read_h3_structure_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的 H3 结构化分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="grid",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_h3_structure_analysis"],
            applicable_scenarios=["兼容旧规划链路", "空间结构复用"],
            produces=["current_h3_structure_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "distribution_pattern": {"type": "string"},
                    "structure_signal_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_h3_structure_analysis,
    )
    registry["read_road_pattern_analysis"] = _register(
        _tool_spec(
            name="read_road_pattern_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的路网结构模式分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="road",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_road_pattern_analysis"],
            applicable_scenarios=["兼容旧规划链路", "路网结构复用"],
            produces=["current_road_pattern_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "metric": {"type": "string"},
                    "node_count": {"type": "integer"},
                    "edge_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_road_pattern_analysis,
    )
    registry["read_population_profile_analysis"] = _register(
        _tool_spec(
            name="read_population_profile_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的人口结构画像",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="population",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_population_profile_analysis"],
            applicable_scenarios=["兼容旧规划链路", "人口画像复用"],
            produces=["current_population_profile_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "view": {"type": "string"},
                    "total_population": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "top_age_band": {"type": "string"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_population_profile_analysis,
    )
    registry["read_nightlight_pattern_analysis"] = _register(
        _tool_spec(
            name="read_nightlight_pattern_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的夜光活力结构分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="nightlight",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_nightlight_pattern_analysis"],
            applicable_scenarios=["兼容旧规划链路", "夜光结构复用"],
            produces=["current_nightlight_pattern_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "view": {"type": "string"},
                    "total_radiance": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "core_hotspot_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_nightlight_pattern_analysis,
    )
    registry["analyze_poi_mix_from_scope"] = _register(
        _tool_spec(
            name="analyze_poi_mix_from_scope",
            description="基于当前 POI 结构结果生成商业画像和功能复合判断",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="poi",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_business_profile", "current_poi_structure_analysis"],
            applicable_scenarios=["兼容旧商业画像链路"],
            produces=["current_business_profile", "current_poi_structure_analysis"],
            readonly=True,
            cost_level="normal",
        ),
        analyze_poi_mix_from_scope,
    )
    registry["detect_commercial_hotspots"] = _register(
        _tool_spec(
            name="detect_commercial_hotspots",
            description="基于 H3 结构结果识别商业核心区、次核心区与机会区",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="grid",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            evidence_contract=["current_commercial_hotspots", "current_h3_structure_analysis"],
            applicable_scenarios=["热点识别", "兼容旧热点链路"],
            produces=["current_commercial_hotspots", "current_h3_structure_analysis", "current_poi_structure_analysis"],
            input_schema={
                "type": "object",
                "properties": {
                    "target_category": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "hotspot_mode": {"type": "string"},
                    "core_zone_count": {"type": "integer"},
                    "opportunity_zone_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
            cost_level="normal",
        ),
        detect_commercial_hotspots_from_scope,
    )
    registry["analyze_target_supply_gap"] = _register(
        _tool_spec(
            name="analyze_target_supply_gap",
            description="基于当前 H3 结构结果判断目标业态供给缺口等级与空间错配",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            evidence_contract=["current_target_supply_gap"],
            applicable_scenarios=["兼容旧补位分析链路", "目标业态缺口判断"],
            cautions=["缺少 H3 gap 结果时只能给弱判断"],
            produces=["current_target_supply_gap", "current_h3_structure_analysis"],
            input_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                },
                "required": ["place_type"],
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "supply_gap_level": {"type": "string"},
                    "gap_mode": {"type": "string"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
            cost_level="normal",
        ),
        analyze_target_supply_gap_from_scope,
    )
    registry["run_business_site_advice"] = _register(
        _tool_spec(
            name="run_business_site_advice",
            description="兼容旧版开店/选址建议组合分析，串联 POI/H3/人口/夜光/路网证据",
            category="action",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="decide",
            llm_exposure="hidden",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            default_policy_key="business_catchment_1km",
            evidence_contract=["business_site_advice", "current_h3_summary", "current_population_summary", "current_nightlight_summary", "current_road_summary"],
            applicable_scenarios=["兼容旧站点建议链路"],
            cautions=["建议新流程优先改用 run_site_selection_pack"],
            requires=["scope_polygon"],
            produces=[
                "business_site_advice",
                "current_pois",
                "current_poi_summary",
                "current_h3",
                "current_h3_grid",
                "current_h3_summary",
                "current_h3_charts",
                "current_population",
                "current_population_summary",
                "current_nightlight",
                "current_nightlight_summary",
                "current_road",
                "current_road_summary",
            ],
            input_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "year": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "max_count": {"type": "integer", "minimum": 1, "maximum": 5000},
                    "resolution": {"type": "integer", "minimum": 0},
                    "include_mode": {"type": "string"},
                    "min_overlap_ratio": {"type": "number", "minimum": 0},
                    "neighbor_ring": {"type": "integer", "minimum": 0},
                    "mode": {"type": "string"},
                    "graph_model": {"type": "string"},
                    "highway_filter": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "types": {"type": "string"},
                    "keywords": {"type": "string"},
                    "poi_count": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "h3_grid_count": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                },
                "required": ["place_type", "types", "keywords"],
                "additionalProperties": True,
            },
            cost_level="expensive",
            timeout_sec=900,
        ),
        run_business_site_advice,
    )

    return registry
